// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPyEDZy2-UKzI4qiGNxWCYdwqOzlSDhW4',
    appId: '1:25477661485:web:6122d1197a4296d3fac9a4',
    messagingSenderId: '25477661485',
    projectId: 'kehadiran-c81c4',
    authDomain: 'kehadiran-c81c4.firebaseapp.com',
    storageBucket: 'kehadiran-c81c4.appspot.com',
    measurementId: 'G-64ZRNL9K9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsmlXuCyxF_cS0mu2Ku8iPinS3-r5CyGY',
    appId: '1:25477661485:android:074de30bb44dc277fac9a4',
    messagingSenderId: '25477661485',
    projectId: 'kehadiran-c81c4',
    storageBucket: 'kehadiran-c81c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCyxZ7YjuS5FF6q5Jv0MwIDR_KS2eNnQs',
    appId: '1:25477661485:ios:aa593684ece81847fac9a4',
    messagingSenderId: '25477661485',
    projectId: 'kehadiran-c81c4',
    storageBucket: 'kehadiran-c81c4.appspot.com',
    iosClientId: '25477661485-pte7vpgmeq6n0g477vdddo3ihh0defuq.apps.googleusercontent.com',
    iosBundleId: 'com.bakti.kehadiran',
  );
}
